### ISSUE TITLE
$set in App/Reducers

### ISSUE THREAD

**Issue by nhducit** [Dattaya/react-boilerplate-object#1]
```
function appReducer(state = initialState, action) {
  switch (action.type) {
    case LOAD_REPOS:
      return update(state, {
        loading: { $set: true },
        error: { $set: false },
        userData: { repositories: { $set: false } },
      });
    case LOAD_REPOS_SUCCESS:
      return update(state, {
        loading: { $set: false },
        currentUser: { $set: action.username },
        userData: { repositories: { $set: action.repos } },
      });
    case LOAD_REPOS_ERROR:
      return { ...state, loading: false, error: action.error };
    default:
      return state;
  }
}
```

**Comment by Dattaya** [comment]
Hi, @nhducit, could you please explain a little bit more what this issue is about? `$set` is from [React immutability helpers](https://facebook.github.io/react/docs/update.html), it is useful when you need to change something deeper, otherwise all of that `...state.substate` is going to look ugly. I now see an official deprecation notice so I'm going to change it to https://github.com/kolodny/immutability-helper.
